### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The gradient of the previous icons are too sharp. Gradients being used should be strong enough to convey the feeling of depth but subtle enough so that user doesn't think that the object's color is an actual gradient (no real object looks like that). Furthermore, I've deleted the 2nd supposed "button" for the smaller icons because at smaller sizes, it just becomes a garbled mess.

There is also an experimental design I would like you to know if it could be used involving spiral on the clock (the app's called rush, so that's the philosophy) on the `data/icons/128`

### CODE REVIEW

**Comment by naaando** [comment]
Thanks for the tip, nice work.
About the spiral I personally didn't like but I wouldn't mind to change if it's chosen with a poll or something.

**Comment by Fatih20** [comment]
I think the spiral would work either after looking at it retrospectively. So, you can delete that.

**Comment by naaando** [comment]
I'm noticing that you changed from png to svg, I think I'll need to reconfigure the assets scripts before merging so it won't break master branch.

**Comment by Fatih20** [comment]
Yeah, because icon should be in svg.

**Comment by naaando** [comment]
Sure, I don't have any problems with the spiral concept at all, but the way it was done with a complementary color and overlapping with the clock pointers would became confusing on a smaller version.

**Comment by Fatih20** [comment]
That is what I'm thinking after looking back at it.

**Comment by Fatih20** [comment]
So, like, when are you going to merge the commit?

**Comment by chances** [comment]
The clock hands are rather difficult to make out on the 16x16 version of the icon. Consider hiding the clock hands for legibility at this size.

**Pull request merged**
